# Generated by Django 3.2 on 2021-04-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210430_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='likes',
        ),
        migrations.AddField(
            model_name='anime',
            name='likes',
            field=models.ManyToManyField(related_name='liked_animes', to='main.User'),
        ),
    ]
